web:
  build: .

  expose:
    - "8080"
  volumes:
    - /usr/src/drfms/public
  links:
    - db
  command: gunicorn -b 127.0.0.1:8080 server:application
db:
  image: mongo:latest

# gunicorn -b 127.0.0.1:8080 server:application
